### ISSUE TITLE
Change to support CRAM

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/cgpNgsQc#6]
If [VerifyBamId](https://github.com/statgen/verifyBamID/issues/2) adds CRAM support remove dependancy on Bio::DB::Sam and switch to [Bio::DB::HTS](http://search.cpan.org/~rishidev/Bio-DB-HTS-1.08/).

This will then be fully BAM/CRAM agnostic.

- [x] Add cram support as below
- [x] #21 / #20 - old hotfix needs pulling into this feature.
- [x] #14 - Upgrade of underlying verifyBamId - Also in dockstore-cgpmap
- [x] #19 - div by zero issues

Modify the perl wrapper to sample the relevant locations from an input CRAM to a temporary BAM:

```
samtools view -F 3844 -L loci.bed -q 10 -b orig.cram | tee new.bam | samtools index - > new.bam.bai
```

Make the applied flags obvious in code:

```
4 - read unmapped (0x4)
256 - not primary alignment (0x100)
512 - read fails platform/vendor quality checks (0x200)
1024 - read is PCR or optical duplicate (0x400)
2048 - supplementary alignment (0x800)
```

**Comment by keiranmraine** [comment]
Investigate suggestion here:

https://github.com/statgen/verifyBamID/issues/2

**Comment by keiranmraine** [comment]
Modify the perl wrapper to sample the relevant locations from an input CRAM to a temporary BAM:

```
samtools view -L loci.bed -q 10 -b orig.cram > new.bam
```

Ensure that mapQ values kept in sync with value for verifyBamId and also test if can drop QCFAIL, DUP and SUPP/SEC when doing this step.

Incorporate hotfix which has been out standing as PR #21 (also #20)

**Comment by keiranmraine** [comment]
- [ ] Add cram support as above
- [ ] #21 / #20 - old hotfix needs pulling into this feature.
- [ ] #14 - Upgrade of underlying verifyBamId - Also in dockstore-cgpmap
- [ ] #19 - div by zero issues
